version: '3.5'
services:
  webserver:
    image: httpd
    hostname: webserver1
    expose:
      - "80"
    volumes:
      - ./html:/usr/local/apache2/htdocs/

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - webserver
    ports:
      - "8080:8080"
